Reorganize code so I can catch the exit status of vmlinuz-version

diff --git a/live-kernel-updater b/live-kernel-updater
--- a/live-kernel-updater
+++ b/live-kernel-updater
@@ -11,6 +11,7 @@
         LIVE_DIR="antiX"
         BOOT_DIR="boot"
 
+ VM_VERSION_PROG="vmlinuz-version"
     LINUXFS_NAME="linuxfs"
     VMLINUZ_NAME="vmlinuz"
   VMLINUZ_2_NAME="vmlinuz1"
@@ -162,7 +163,7 @@ main() {
     EXIT_NUM=100
     [ $UID -eq 0 ] || fatal 101 "This script must be run as root"
 
-    need_prog vmlinuz-version copy-initrd-modules
+    need_prog $VM_VERSION_PROG copy-initrd-modules
 
     trap clean_up EXIT
 
@@ -286,11 +287,12 @@ main() {
     local both_vm=$VMLINUZ_NAME
     [ -n "$sVMLINUZ_2_NAME" ] && both_vm="$both_vm|$VMLINUZ_2_NAME"
 
-    local live_all=$(get_all_kernel "$full_live_dir")                         # all in live dir
-    local boot_all=$(get_all_kernel "$full_boot_dir")                         # all in boot dir
-    local boot_mod=$(get_all_kernel "$full_boot_dir" --mod-dir="$root_dir")   # boot dir with module dir
+    local live_all boot_all
+    get_all_kernel live_all "$full_live_dir"                          # all in live dir
+    get_all_kernel boot_all "$full_boot_dir"                          # all in boot dir
+    #get_all_kernel boot_mod "$full_boot_dir" --mod-dir="$root_dir"   # boot dir with module dir
 
-    local live_vm=$(find_kernel_fname "$both_vm" "$live_all")                 # live with default vmlinuz names
+    local live_vm=$(find_kernel_fname "$both_vm" "$live_all")         # live with default vmlinuz names
     local vm_cnt=$(count_lines "$live_vm")
     local live_old=$(find_kernel_fname "($both_vm)$KOLD_EXT" "$live_all" )
 
@@ -314,10 +316,10 @@ main() {
     msg_kernel "$boot_new"  "new installed kernel"    "new installed kernels"
 
     show_kernel_3 "Live Kernels:" "$live_all" | strip_color >> $LOG_FILE
-    show_kernel_3 "Boot Kernels:" "$boot_mod" | strip_color >> $LOG_FILE
+    show_kernel_3 "Boot Kernels:" "$boot_all" | strip_color >> $LOG_FILE
 
     fatal_k0 "$boot_all" $"No kernels found in the boot directory"
-    fatal_k0 "$boot_mod" $"No valid kernels found in the boot directory"
+    #fatal_k0 "$boot_mod" $"No valid kernels found in the boot directory"
     fatal_k0 "$live_all"  $"No kernels found in the live boot directory"
 
     if [ $new_cnt -eq 0 ]; then
@@ -722,7 +724,13 @@ do_rollback() {
 #
 # count_lines         Count lines in a variable, number of kernels in a list
 #------------------------------------------------------------------------------
-get_all_kernel()      { vmlinuz-version -nsr --delimit="$K_IFS" "$@"        ;}
+get_all_kernel() {
+    local  var=$1 temp ; shift
+    temp=$($VM_VERSION_PROG -nsr --delimit="$K_IFS" "$@") \
+        || fatal "The %s program failed!" "$VM_VERSION_PROG"
+
+    eval $var=\$temp
+}
 
 get_kernel_version()  { echo "$1" | cut -d"$K_IFS" -f1                      ;}
 get_kernel_fname()    { echo "$1" | cut -d"$K_IFS" -f2                      ;}
