Make lib_dir work with repos and installed (repos have priority)

diff --git a/live-kernel-updater b/live-kernel-updater
--- a/live-kernel-updater
+++ b/live-kernel-updater
@@ -1,7 +1,9 @@
 #!/bin/bash
 
-ME=${0##*/}
-MY_DIR=$(dirname "$(readlink -f $0)")
+        ME=${0##*/}
+    MY_DIR=$(dirname "$(readlink -f $0)")
+MY_LIB_DIR=$(readlink -f "$MY_DIR/../cli-shell-utils")
+   LIB_DIR="/usr/local/lib/cli-shell-utils"
 
 #== BEGIN_CONFIG
 
@@ -39,7 +41,6 @@ MIN_LINUXFS_SIZE="100M"
 
 #== END_CONFIG
 
-        LIB_PATH="/usr/local/lib/shell-utils"
         WORK_DIR="/run/$ME"
             FIFO="/run/$ME/fifo"
        LOCK_FILE="/run/lock/$ME"
@@ -52,7 +53,9 @@ MIN_LINUXFS_SIZE="100M"
        ALL_FORCE="all,flock,clear,compress,usb,umount"
        ALL_PAUSE="all,fifo,mount,unpack,copy,repack,clean"
 
-            PATH="$MY_DIR:/usr/local/share/$ME/bin:$PATH"
+        LIB_PATH="$MY_LIB_DIR:$LIB_DIR"
+            PATH="$MY_LIB_DIR/bin:$LIB_DIR/bin:$PATH"
+
 
 usage() {
     local ret=${1:-0}
@@ -870,32 +873,6 @@ clean_up() {
     rm -f $LOCK_FILE
 }
 
-#------------------------------------------------------------------------------
-# Excessive code to try to load the dang library file.
-#------------------------------------------------------------------------------
-load_lib() {
-    local file=$1 path=$2
-
-    unset FOUND_LIB
-    local dir lib found orig_ifs=$IFS
-    IFS=:
-    for dir in $path; do
-        lib=$dir/$file
-        test -r $lib || continue
-        if ! . $lib; then
-            printf "Error when loading library %s\n" "$lib" >&2
-            printf "This is a fatal error\n" >&2
-            exit 15
-        fi
-        FOUND_LIB=$lib
-        IFS=$orig_ifs
-        return 0
-    done
-
-    printf "Could not find library '%s' on path '%s'\n" "$file" "$path" >&2
-    printf "This is a fatal error\n" >&2
-    exit 17
-}
 
 write_config() {
     local file=${1:-$CONFIG_FILE}
@@ -939,8 +916,33 @@ Config_File
 
     return 0
 }
+
+#------------------------------------------------------------------------------
+#
+#------------------------------------------------------------------------------
+load_lib() {
+    local file=$1 path=$2
+    unset FOUND_LIB
+
+    local dir lib found IFS=:
+    for dir in $path; do
+        lib=$dir/$file
+        test -r $lib || continue
+        if ! . $lib; then
+            printf "Error when loading library %s\n" "$lib" >&2
+            printf "This is a fatal error\n" >&2
+            exit 15
+        fi
+        FOUND_LIB=$lib
+        return 0
+    done
+
+    printf "Could not find library '%s' on path '%s'\n" "$file" "$path" >&2
+    printf "This is a fatal error\n" >&2
+    exit 17
+}
+
 #===== Start Here =============================================================
-LIB_PATH="$LIB_PATH:$MY_DIR/../cli-shell-utils:$MY_DIR"
 load_lib "$SHELL_LIB" "$LIB_PATH"
 
 set_colors
